//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.26 at 04:23:10 PM EEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://docs.oasis-open.org/ns/energyinterop/201110/payloads", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns = {
    @jakarta.xml.bind.annotation.XmlNs(namespaceURI = "http://docs.oasis-open.org/ns/energyinterop/201110/payloads", prefix = "pyld")
})
package com.qcharge.openadr.model.oadr20b.pyld;
