//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.26 at 04:23:10 PM EEST 
//


package com.qcharge.openadr.model.oadr20b.emix;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import com.qcharge.openadr.model.oadr20b.oadr.BaseUnitType;
import com.qcharge.openadr.model.oadr20b.oadr.CurrencyType;
import com.qcharge.openadr.model.oadr20b.oadr.CurrentType;
import com.qcharge.openadr.model.oadr20b.oadr.FrequencyType;
import com.qcharge.openadr.model.oadr20b.oadr.OadrGBItemBase;
import com.qcharge.openadr.model.oadr20b.oadr.PulseCountType;
import com.qcharge.openadr.model.oadr20b.oadr.TemperatureType;
import com.qcharge.openadr.model.oadr20b.oadr.ThermType;
import com.qcharge.openadr.model.oadr20b.power.EnergyItemType;
import com.qcharge.openadr.model.oadr20b.power.PowerItemType;
import com.qcharge.openadr.model.oadr20b.power.VoltageType;


/**
 * Abstract base type for units for EMIX Product delivery, measurement, and warrants.
 * 
 * <p>Java class for ItemBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemBaseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemBaseType")
@XmlSeeAlso({
    VoltageType.class,
    EnergyItemType.class,
    PowerItemType.class,
    BaseUnitType.class,
    CurrentType.class,
    CurrencyType.class,
    FrequencyType.class,
    ThermType.class,
    TemperatureType.class,
    PulseCountType.class,
    OadrGBItemBase.class
})
public abstract class ItemBaseType {


}
