//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.26 at 04:23:10 PM EEST 
//


package com.qcharge.openadr.model.oadr20b.emix;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import com.qcharge.openadr.model.oadr20b.gml.FeatureCollection;


/**
 * The Service Area is the geographic region that is affected by the EMIX market condition
 * 
 * <p>Java class for ServiceAreaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceAreaType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.opengis.net/gml/3.2}FeatureCollection"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceAreaType", propOrder = {
    "featureCollection"
})
public class ServiceAreaType {

    @XmlElement(name = "FeatureCollection", namespace = "http://www.opengis.net/gml/3.2", required = true)
    protected FeatureCollection featureCollection;

    /**
     * Gets the value of the featureCollection property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureCollection }
     *     
     */
    public FeatureCollection getFeatureCollection() {
        return featureCollection;
    }

    /**
     * Sets the value of the featureCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureCollection }
     *     
     */
    public void setFeatureCollection(FeatureCollection value) {
        this.featureCollection = value;
    }

}
