//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.26 at 04:23:10 PM EEST 
//


package com.qcharge.openadr.model.oadr20b.oadr;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for currencyItemDescriptionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="currencyItemDescriptionType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="currency"/&gt;
 *     &lt;enumeration value="currencyPerKW"/&gt;
 *     &lt;enumeration value="currencyPerKWh"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "currencyItemDescriptionType")
@XmlEnum
public enum CurrencyItemDescriptionType {

    @XmlEnumValue("currency")
    CURRENCY("currency"),
    @XmlEnumValue("currencyPerKW")
    CURRENCY_PER_KW("currencyPerKW"),
    @XmlEnumValue("currencyPerKWh")
    CURRENCY_PER_K_WH("currencyPerKWh");
    private final String value;

    CurrencyItemDescriptionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CurrencyItemDescriptionType fromValue(String v) {
        for (CurrencyItemDescriptionType c: CurrencyItemDescriptionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
