//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.26 at 04:23:10 PM EEST 
//


package com.qcharge.openadr.model.oadr20b.oadr;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="oadrKey" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="oadrValue" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "oadrKey",
    "oadrValue"
})
@XmlRootElement(name = "oadrInfo")
public class OadrInfo {

    @XmlElement(required = true)
    protected String oadrKey;
    @XmlElement(required = true)
    protected String oadrValue;

    /**
     * Gets the value of the oadrKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOadrKey() {
        return oadrKey;
    }

    /**
     * Sets the value of the oadrKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOadrKey(String value) {
        this.oadrKey = value;
    }

    /**
     * Gets the value of the oadrValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOadrValue() {
        return oadrValue;
    }

    /**
     * Sets the value of the oadrValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOadrValue(String value) {
        this.oadrValue = value;
    }

}
