//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.26 at 04:23:10 PM EEST 
//


package com.qcharge.openadr.model.oadr20b.oadr;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for oadrTransportType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="oadrTransportType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="simpleHttp"/&gt;
 *     &lt;enumeration value="xmpp"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "oadrTransportType")
@XmlEnum
public enum OadrTransportType {

    @XmlEnumValue("simpleHttp")
    SIMPLE_HTTP("simpleHttp"),
    @XmlEnumValue("xmpp")
    XMPP("xmpp");
    private final String value;

    OadrTransportType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OadrTransportType fromValue(String v) {
        for (OadrTransportType c: OadrTransportType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
