//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.26 at 04:23:10 PM EEST 
//


package com.qcharge.openadr.model.oadr20b.oadr;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for oadrSamplingRateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="oadrSamplingRateType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="oadrMinPeriod" type="{urn:ietf:params:xml:ns:icalendar-2.0}DurationValueType"/&gt;
 *         &lt;element name="oadrMaxPeriod" type="{urn:ietf:params:xml:ns:icalendar-2.0}DurationValueType"/&gt;
 *         &lt;element name="oadrOnChange" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "oadrSamplingRateType", propOrder = {
    "oadrMinPeriod",
    "oadrMaxPeriod",
    "oadrOnChange"
})
public class OadrSamplingRateType {

    @XmlElement(required = true)
    protected String oadrMinPeriod;
    @XmlElement(required = true)
    protected String oadrMaxPeriod;
    protected boolean oadrOnChange;

    /**
     * Gets the value of the oadrMinPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOadrMinPeriod() {
        return oadrMinPeriod;
    }

    /**
     * Sets the value of the oadrMinPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOadrMinPeriod(String value) {
        this.oadrMinPeriod = value;
    }

    /**
     * Gets the value of the oadrMaxPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOadrMaxPeriod() {
        return oadrMaxPeriod;
    }

    /**
     * Sets the value of the oadrMaxPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOadrMaxPeriod(String value) {
        this.oadrMaxPeriod = value;
    }

    /**
     * Gets the value of the oadrOnChange property.
     * 
     */
    public boolean isOadrOnChange() {
        return oadrOnChange;
    }

    /**
     * Sets the value of the oadrOnChange property.
     * 
     */
    public void setOadrOnChange(boolean value) {
        this.oadrOnChange = value;
    }

}
