//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.26 at 04:23:10 PM EEST 
//


package com.qcharge.openadr.model.oadr20b.oadr;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;
import com.qcharge.openadr.model.oadr20b.ei.ReportPayloadType;


/**
 * Report payload for use in reports.
 * 
 * <p>Java class for oadrReportPayloadType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="oadrReportPayloadType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://docs.oasis-open.org/ns/energyinterop/201110}ReportPayloadType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrDataQuality" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "oadrReportPayloadType", propOrder = {
    "oadrDataQuality"
})
public class OadrReportPayloadType
    extends ReportPayloadType
{

    protected String oadrDataQuality;

    /**
     * Enumerated value for the quality of this data item
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOadrDataQuality() {
        return oadrDataQuality;
    }

    /**
     * Sets the value of the oadrDataQuality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOadrDataQuality(String value) {
        this.oadrDataQuality = value;
    }

}
