//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.26 at 04:23:10 PM EEST 
//


package com.qcharge.openadr.model.oadr20b.oadr;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResponseRequiredType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ResponseRequiredType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="always"/&gt;
 *     &lt;enumeration value="never"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ResponseRequiredType")
@XmlEnum
public enum ResponseRequiredType {


    /**
     * Always send a response for every event received.
     * 
     */
    @XmlEnumValue("always")
    ALWAYS("always"),

    /**
     * Never respond.
     * 
     */
    @XmlEnumValue("never")
    NEVER("never");
    private final String value;

    ResponseRequiredType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ResponseRequiredType fromValue(String v) {
        for (ResponseRequiredType c: ResponseRequiredType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
