//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.26 at 04:23:10 PM EEST 
//


package com.qcharge.openadr.model.oadr20b.ei;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import com.qcharge.openadr.model.oadr20b.avob.PayloadAvobVenServiceRequestType;
import com.qcharge.openadr.model.oadr20b.avob.PayloadKeyTokenType;
import com.qcharge.openadr.model.oadr20b.oadr.OadrPayloadResourceStatusType;


/**
 * Base for information in signal / baseline / report payloads
 * 
 * <p>Java class for PayloadBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PayloadBaseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PayloadBaseType")
@XmlSeeAlso({
    PayloadFloatType.class,
    OadrPayloadResourceStatusType.class,
    PayloadKeyTokenType.class,
    PayloadAvobVenServiceRequestType.class
})
public abstract class PayloadBaseType {


}
